[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synapse-shield"
version = "0.2.2"
authors = [
  { name="Mustafa Güngör", email="mustafagungor181881@gmail.com" },
]
description = "Next-Gen Open-Source Behavioral Biometrics & Bot Mitigation Engine"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
keywords = [
  "cybersecurity", "bot-detection", "turnstile-alternative",
  "behavioral-biometrics", "kinematics", "fastapi", "zero-pii"
]
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.29.0",
    "numpy>=1.26.0",
    "scikit-learn>=1.4.0",
]

[project.scripts]
synapse-shield = "synapse_shield.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"synapse_shield" = ["static/*"]

[project.urls]
Homepage = "https://github.com/0xStoic-bit/Synapse_Shield"